### ISSUE TITLE
About the number of layers in blocks

### ISSUE THREAD

**Issue by ZhuMai** [iboing/CliqueNet#11]
The description of the number of layers in blocks seems mix the cases having bottleneck layers with the cases without bottleneck layers in your paper according to your code. 
All the models for ImageNet have bottleneck layers. The title of Table 3 and the code indicate that the number of layers refers to the times of growth. One model for CIFAR, CliqueNet (k = 150; T = 30), has bottleneck layers too. The title of Table 4 shown that T is the total number of layers in three blocks. On the contrary, your code indicate that the number is 15 actually with the same meaning as the models for ImageNet.
If my understanding is correct, the description in your paper really mislead readers. It is better to comment on it.

**Comment by iboing** [comment]
Bottleneck layers (if enable) are also counted for T. So CliqueNet (k=150; T=30) has the same configurations with CliqueNet (k=150; 15) without bottleneck. Sorry about ambiguity.
