### ISSUE TITLE
Error in load_state_dict with your pretrained model

### ISSUE THREAD

**Issue by mzemlyanikin** [iboing/CliqueNet#12]
Hi! Thanks for a nice network.
I have a problem. When I try to continue training with pretrained model that you shared I get 
`KeyError: 'unexpected key "module.block1.conv_param.1.weight" in state_dict'`

**Comment by iboing** [comment]
Hi! The error is due to the modification of original code. The keys in this pre-trained model have been updated.  Please download again.

**Comment by mzemlyanikin** [comment]
Thanks a lot for your quick response!
