### ISSUE TITLE
Maybe something wrong in ‘/imagenet_pytorch/utils.py’？

### ISSUE THREAD

**Issue by tinyRattar** [iboing/CliqueNet#2]
I noticed that:

in file ‘/imagenet_pytorch/utils.py’ 
line 152 
`block_feature_II = torch.cat((block_feature_II, self.blob_dict_list[1][str(layer_id)]), 1)`

maybe the `self.blob_dict_list[1]` should be replaced with `self.blob_dict_list[self.loop_num]`
to get the final loop result instead of the first loop result?

**Comment by zs-zhong** [comment]
Hi,

You are right.  When we debuged our code, we always set `loop_num = 1`. It does not matter. We have rewritten it. Thanks!

**Comment by tinyRattar** [comment]
Thank you for your notice! 
I checked the code again,
but it might be `self.loop_num` not `self.layer_num`?

**Comment by zs-zhong** [comment]
sorry, error has been fixed.
