### ISSUE TITLE
Maybe something wrong in "./models/utils.py"

### ISSUE THREAD

**Issue by hythbr** [iboing/CliqueNet#3]
The code in Line 350 in “./models/utils.py” maybe wrong,
    stage_II=tf.concat((stage_II, blob_dict[str(layer_id)]), axis=3)  .
 The "blob_dict" may be "blob_dict_new" , since here is the Stage-II feature which is inputted to the next
block.

**Comment by iboing** [comment]
You are right, thanks for notification! The bug has been fixed. 
Don't worry about the results provided, because the typo just happened when we modified our code to release.
